uint8 red                       # red component of rgb color
uint8 green                     # green component of rgb color
uint8 blue                      # blue component of rgb color
float32 height                  # height corresponding to the pixel
uint16 ul                       # corresponding abscissa on left image
uint16 ur                       # corresponding abscissa on right image
uint16 v                        # corresponding ordinate on both images
