uint8 op
string calName
int8 calPointId
uint8 OP_LOAD_CALIB=0
uint8 OP_SAVE_CALIB=1
uint8 OP_START_CALIB=2
uint8 OP_ABORT_CALIB=3
uint8 OP_NEXT_POINT=4
uint8 OP_SET_POINT=5
uint8 OP_RUN_TRANSFORM=6
---
bool err
int8 calPointId
